# Generated by Django 2.0.1 on 2021-08-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'ordering': ('amount',), 'verbose_name_plural': 'تخفیف امتیازی'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['start_date'], 'verbose_name_plural': 'سفارش ها'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'جزئیات سفارش'},
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='amount',
            field=models.CharField(max_length=20, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=20, verbose_name='کد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='from_date',
            field=models.DateField(verbose_name='از تاریخ'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='to_date',
            field=models.DateField(verbose_name=' تا تاریخ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(verbose_name='تاریخ ثبت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.CharField(default=0, max_length=100, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='موجودی'),
        ),
    ]
